### ISSUE TITLE
Can't import `graphql-mocks` using ESM

### ISSUE THREAD

**Issue by bengry** [graphql-mocks/graphql-mocks#251]
I'm trying to follow the docs on using `graphql-mocks` with Playwright and getting an error:
```
SyntaxError: The requested module 'graphql-mocks' does not provide an export named 'GraphQLHandler'
```
![CleanShot 2024-07-11 at 13 11 18@2x](https://github.com/graphql-mocks/graphql-mocks/assets/260431/68f7da43-00f0-41eb-b219-2e2254bf4d7c)

I created a minimal repro for this: https://github.com/bengry/graphql-mocks-import-error-repro:
```console
> git clone https://github.com/bengry/graphql-mocks-import-error-repro
> cd graphql-mocks-import-error-repro
> yarn install
> yarn playwright test --ui
```
Note that it uses Playwright, but I think the same happens regardless when using ESM:
```
// test.mjs
import { GraphQLHandler } from "graphql-mocks";

const handler = new GraphQLHandler({
  dependencies: { graphqlSchema: "" },
});
```
and run it using node:
```
> node test.mjs
```
You get this error:
```console
import { GraphQLHandler } from "graphql-mocks";
         ^^^^^^^^^^^^^^
SyntaxError: Named export 'GraphQLHandler' not found. The requested module 'graphql-mocks' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'graphql-mocks';
const { GraphQLHandler } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:132:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:214:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.1
```

Please advise, this is obviously blocking any usage of `graphql-mocks` for us 😢

**Comment by chadian** [comment]
Hello! Thanks for the clear reproduction steps. I've just pushed a fix for es modules with node to all the packages. In your repo https://github.com/bengry/graphql-mocks-import-error-repro, I've made the following changes locally with the latest packages:

```diff
diff --git a/package.json b/package.json
index 3c3ec1e..e7b0bd3 100644
--- a/package.json
+++ b/package.json
@@ -6,9 +6,9 @@
     "test-head": "npx playwright test --ui"
   },
   "devDependencies": {
-    "@graphql-mocks/network-playwright": "^0.1.1",
+    "@graphql-mocks/network-playwright": "^0.2.0",
     "@playwright/test": "^1.45.1",
-    "graphql-mocks": "^0.10.0",
+    "graphql-mocks": "^0.11.0",
     "typescript": "^5.5.3"
   },
   "packageManager": "yarn@4.3.1"
```

And now when I run the test I get:
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/d6fdad08-7af2-4169-a85b-39f2e6f0dc7e">

Which is an expected error in this repo since the schema of an empty string isn't a valid GraphQL Schema.

Changing the setup to:
```diff
diff --git a/tests/ui.example.spec.ts b/tests/ui.example.spec.ts
index debbedc..69b18b2 100644
--- a/tests/ui.example.spec.ts
+++ b/tests/ui.example.spec.ts
@@ -5,7 +5,15 @@ import { GraphQLHandler } from "graphql-mocks";
 
 const graphqlHandler = new GraphQLHandler({
   dependencies: {
-    graphqlSchema: "",
+    graphqlSchema: `
+      schema {
+        query: Query
+      }
+      
+      type Query {
+        hello: String
+      }
+    `,
   },
 });
```

And the test passes with no error in created the `GraphQLHandler`.

Let me know if you run into any issues, and thanks again for the clearly written issue.

**Comment by bengry** [comment]
Thanks @chadian. The update has fixed the issue.

I'm still seeing slowness when starting up the Playwright browser, but I'm not sure if it's due to `graphql-mocks` or the surrounding ecosystem (`@graphql-tools/*`). I'll monitor it further and open a separate issue if it's an issue with `graphql-mocks`.
